// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class AssignLocationHistory
{
    public long? CandidateId { get; set; }

    public int? AssignedLocation { get; set; }

    public string AssignedReason { get; set; }

    public bool? IsActive { get; set; }

    public DateTime AssignedOnDate { get; set; }

    public DateTime? ReleasedOnDate { get; set; }

    public int AssignLocationHistoryId { get; set; }

    public virtual TblLocation AssignedLocationNavigation { get; set; }

    public virtual Candidate Candidate { get; set; }
}