// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Attendance
{
    public int DcAttendanceId { get; set; }

    public int Ecode { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public string Status { get; set; }

    public DateTime SubmitOn { get; set; }

    public virtual Employee EcodeNavigation { get; set; }
}