// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class BulkEmployeeMasternewnew
{
    public string Ecode { get; set; }

    public string Fullname { get; set; }

    public string Location { get; set; }

    public string Gender { get; set; }

    public string Dob { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string Doj { get; set; }

    public string Column8 { get; set; }

    public string Column9 { get; set; }
}