// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Bulkorgdatum
{
    public string Ecode { get; set; }

    public string Employeename { get; set; }

    public string ReportingHeadEcode { get; set; }

    public string ManagerName { get; set; }

    public string EffectiveDate { get; set; }
}