// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class BulkEmployeeMaster
{
    public string Ecode { get; set; }

    public string Title { get; set; }

    public string FullName { get; set; }

    public string FatherSName { get; set; }

    public string MotherSName { get; set; }

    public string PasportSizePhoto { get; set; }

    public string Dob { get; set; }

    public string Gender { get; set; }

    public string PanNo { get; set; }

    public string AadharNo { get; set; }

    public string NameOnAdhar { get; set; }

    public string PlaceOfBirth { get; set; }

    public string PresentAddress { get; set; }

    public string PresentAddressPinCode { get; set; }

    public string PermanentAddress { get; set; }

    public string MaritialStatus { get; set; }

    public string Mobile { get; set; }

    public string EmailAddress { get; set; }

    public string Nationality { get; set; }

    public string Religion { get; set; }

    public string BankName { get; set; }

    public string ACNo { get; set; }

    public string BankIfscCode { get; set; }

    public string Reference1OfLast3Company { get; set; }

    public string Contact1OfLast3Company { get; set; }

    public string Reference2OfLast3Company1 { get; set; }

    public string Contact2OfLast3Company1 { get; set; }

    public string Reference3OfLast3Company11 { get; set; }

    public string Contact3OfLast3Company11 { get; set; }

    public string Reference4OfLast3Company11 { get; set; }

    public string Contact4OfLast3Company11 { get; set; }

    public string Reference5OfLast3Company111 { get; set; }

    public string Contact5OfLast3Company111 { get; set; }

    public string FamilyMemberName { get; set; }

    public string FamilyMemberRelation { get; set; }

    public string FamilyMemberDob { get; set; }

    public string Company1 { get; set; }

    public string Company2 { get; set; }

    public string Company3 { get; set; }

    public string WorkLocation { get; set; }

    public string PositionHeldInPreviousCompany { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string InHandSalary { get; set; }

    public string LastCtcAnnual { get; set; }

    public string HighestQualification { get; set; }

    public string Column46 { get; set; }

    public string Column47 { get; set; }

    public string Ecode1 { get; set; }

    public string Designation { get; set; }

    public string Department { get; set; }

    public string Location { get; set; }

    public string Doj { get; set; }

    public string DateOfResignation { get; set; }

    public string DateOfLeft { get; set; }

    public string Isresgined { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string ReportingHeadEcode { get; set; }

    public string Mobile2 { get; set; }
}