// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class BulkRegionMaster
{
    public string Stcode { get; set; }

    public string RegionName { get; set; }

    public string StateName { get; set; }
}