// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Candidate
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string HusbandName { get; set; }

    public string FatherName { get; set; }

    public string MotherName { get; set; }

    public string Designation { get; set; }

    public string Location { get; set; }

    public DateOnly? Dob { get; set; }

    public string Gender { get; set; }

    public string Department { get; set; }

    public DateTime? JoiningDate { get; set; }

    public decimal? GrossSalary { get; set; }

    public string UanNo { get; set; }

    public string PanNo { get; set; }

    public string AadharNo { get; set; }

    public string NameOnAadhar { get; set; }

    public string Udf1 { get; set; }

    public string PlaceOfBirth { get; set; }

    public string PresentAddress { get; set; }

    public string PresentAddressPinCode { get; set; }

    public string PermanentAddress { get; set; }

    public string PermanentAddressPinCode { get; set; }

    public string EmpCode { get; set; }

    public string ApplicantCode { get; set; }

    public string WeeklyOff { get; set; }

    public string MaritialStatus { get; set; }

    public string Mobile { get; set; }

    public string EmailAddress { get; set; }

    public bool? Isrelativeincompany { get; set; }

    public string Nationality { get; set; }

    public string Religion { get; set; }

    public string BankName { get; set; }

    public string ACNo { get; set; }

    public string BankIfscCode { get; set; }

    public string Reference1OfLast3Company { get; set; }

    public string Contact1OfLast3Company { get; set; }

    public string Reference2OfLast3Company { get; set; }

    public string Contact2OfLast3Company { get; set; }

    public string Reference3OfLast3Company { get; set; }

    public string Contact3OfLast3Company { get; set; }

    public string Reference4OfLast3Company { get; set; }

    public string Contact4OfLast3Company { get; set; }

    public string Reference5OfLast3Company { get; set; }

    public string Contact5OfLast3Company { get; set; }

    public string FamilyMemberName { get; set; }

    public string FamilyMemberRelation { get; set; }

    public DateOnly? FamilyMemberDob { get; set; }

    public string Company1 { get; set; }

    public string Company2 { get; set; }

    public string Company3 { get; set; }

    public string WorkLocation { get; set; }

    public string PositionHeldInPreviousCompany { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string InHandSalary { get; set; }

    public string LastCtcAnnual { get; set; }

    public string HighestQualification { get; set; }

    public string BeneficiaryAddress { get; set; }

    public string PrevEstNo { get; set; }

    public string Reference { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsSalarySlipUploaded { get; set; }

    public bool? IsBankStatementUploaded { get; set; }

    public bool? IsPrevOfferLetterUploaded { get; set; }

    public bool? IsPassportPhotoUploaded { get; set; }

    public bool? IsPanAttachmentUploaded { get; set; }

    public bool? IsAadharAttachmentUploaded { get; set; }

    public bool? IsBankPassbookAttachmentUpoaded { get; set; }

    public bool? IsEducationAttachmentUploaded { get; set; }

    public int? StatusId { get; set; }

    public string ApplicantId { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? Hra { get; set; }

    public decimal? Cca { get; set; }

    public decimal? SpecialAllowance { get; set; }

    public decimal? Da { get; set; }

    public decimal? ExtraAllowance { get; set; }

    public decimal? MonthlyGrossCtc { get; set; }

    public decimal? AnnuallyNetCtc { get; set; }

    public bool? IsResumeUploaded { get; set; }

    public decimal? TotalExperience { get; set; }

    public decimal? SalaryExpectation { get; set; }

    public string AdditionalInfoApplicant { get; set; }

    public bool? Agreement { get; set; }

    public bool? IsApplicant { get; set; }

    public bool? IsApplicantApproved { get; set; }

    public bool? Pfapplicable { get; set; }

    public bool? BonusApplicable { get; set; }

    public bool? Esicapplicable { get; set; }

    public int? CompanyId { get; set; }

    public bool? IsEvaluationAttachmentUploaded { get; set; }

    public bool? IsOfferLetterAttachmentUploaded { get; set; }

    public bool? IsInterviewVideoUploaded { get; set; }

    public string ReportHeadEcode { get; set; }

    public virtual ICollection<AssignLocationHistory> AssignLocationHistories { get; set; } = new List<AssignLocationHistory>();

    public virtual ICollection<CandidateStatusHistory> CandidateStatusHistories { get; set; } = new List<CandidateStatusHistory>();

    public virtual ICollection<InterviewRound> InterviewRounds { get; set; } = new List<InterviewRound>();

    public virtual TblStatus Status { get; set; }

    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();

    public virtual ICollection<TblNewCandidateApproval> TblNewCandidateApprovals { get; set; } = new List<TblNewCandidateApproval>();
}