// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class CandidateStatusHistory
{
    public int HistoryId { get; set; }

    public long? CandidateId { get; set; }

    public int? StatusId { get; set; }

    public string Hrname { get; set; }

    public DateOnly? CallDate { get; set; }

    public TimeOnly? CallStartTime { get; set; }

    public TimeOnly? CallEndTime { get; set; }

    public string CallResponse { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual CandidateStatus Status { get; set; }
}