// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class CandidateStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<CandidateStatusHistory> CandidateStatusHistories { get; set; } = new List<CandidateStatusHistory>();
}