// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class CanidateDoc
{
    public long Id { get; set; }

    public long Cid { get; set; }

    public string FilePath { get; set; }

    public string FileType { get; set; }

    public string FileSize { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }
}