// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Employee
{
    public int Ecode { get; set; }

    public string EmpName { get; set; }

    public string EmailId { get; set; }

    public bool IsContract { get; set; }

    public string Designation { get; set; }

    public string Department { get; set; }

    public string SubDepartment { get; set; }

    public string ReportingManagerName { get; set; }

    public string RptPersonCard { get; set; }

    public bool ActInAct { get; set; }

    public string PasswordHash { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();
}