// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class fn_GetMonthlyPunchesRange_newResult
    {
        public int? EmpAttendanceId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        public string ECode { get; set; }
        public DateOnly? AttendanceDate { get; set; }
        [StringLength(8000)]
        public string Machine_Type { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public TimeOnly Punch1 { get; set; }
        public TimeOnly Punch2 { get; set; }
        public TimeOnly Punch3 { get; set; }
        public TimeOnly Punch4 { get; set; }
        public TimeOnly Punch5 { get; set; }
        public TimeOnly Punch6 { get; set; }
        public TimeOnly Punch7 { get; set; }
        public TimeOnly Punch8 { get; set; }
        public TimeOnly Punch9 { get; set; }
        public TimeOnly Punch10 { get; set; }
        public TimeOnly Punch11 { get; set; }
        public TimeOnly Punch12 { get; set; }
        public TimeOnly? PunchIn { get; set; }
        public TimeOnly? PunchOut { get; set; }
        public TimeOnly? RegularizePunchIn { get; set; }
        public TimeOnly? RegularizePunchOut { get; set; }
        public bool? IsRegularize { get; set; }
        public bool? IsOnLeave { get; set; }
        public int? TotalWorkingMinutes { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
    }
}
