// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class fn_GetMonthlyPunchesRange_productionnewResult
    {
        public int? EmpAttendanceId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        public string ECode { get; set; }
        public DateOnly? AttendanceDate { get; set; }
        [StringLength(4000)]
        public string Machine_Type { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(8)]
        public string Punch1 { get; set; }
        [StringLength(8)]
        public string Punch2 { get; set; }
        [StringLength(8)]
        public string Punch3 { get; set; }
        [StringLength(8)]
        public string Punch4 { get; set; }
        [StringLength(8)]
        public string Punch5 { get; set; }
        [StringLength(8)]
        public string Punch6 { get; set; }
        [StringLength(8)]
        public string Punch7 { get; set; }
        [StringLength(8)]
        public string Punch8 { get; set; }
        [StringLength(8)]
        public string Punch9 { get; set; }
        [StringLength(8)]
        public string Punch10 { get; set; }
        [StringLength(8)]
        public string Punch11 { get; set; }
        [StringLength(8)]
        public string Punch12 { get; set; }
        public TimeOnly? PunchIn { get; set; }
        public TimeOnly? PunchOut { get; set; }
        public TimeOnly RegularizePunchIn { get; set; }
        public TimeOnly RegularizePuncOut { get; set; }
        public bool? IsRegularize { get; set; }
        public bool? IsOnLeave { get; set; }
        [StringLength(5)]
        public string TotalWorkingMinutes { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
        public int? TotalWorkingDays { get; set; }
    }
}
