// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class fn_GetDailyPunchStatus_DemoResult
    {
        public long EmployeeId { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        public DateOnly PunchDate { get; set; }
        [StringLength(8)]
        public string PunchIn { get; set; }
        [StringLength(8)]
        public string PunchOut { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
    }
}
