// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class GetApplicantsWithPaginationAndSearchResult
    {
        public long Id { get; set; }
        [StringLength(100)]
        public string ApplicantId { get; set; }
        public bool? IsApplicant { get; set; }
        [StringLength(2147483647)]
        public string FirstName { get; set; }
        [StringLength(2147483647)]
        public string EmailAddress { get; set; }
        [StringLength(2147483647)]
        public string AadharNo { get; set; }
        public DateOnly? DOB { get; set; }
        [StringLength(2147483647)]
        public string Mobile { get; set; }
        public int? StatusId { get; set; }
        [StringLength(2147483647)]
        public string DesignationId { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
    }
}
