// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class GetEmployeeDetailsResult
    {
        public long EmployeeId { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(100)]
        public string ReportHeadEcode { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
