// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class GetEmployeeDetailsforexcelWITHOUTFILTERResult
    {
        [Column("Employee Code")]
        [StringLength(20)]
        public string EmployeeCode { get; set; }
        [Column("Name of Employee")]
        [StringLength(100)]
        public string NameofEmployee { get; set; }
        [Column("Posted Location")]
        [StringLength(255)]
        public string PostedLocation { get; set; }
        [Column("Joined Location")]
        [StringLength(255)]
        public string JoinedLocation { get; set; }
        [StringLength(10)]
        public string Sex { get; set; }
        [Column("D.O.B.")]
        [StringLength(10)]
        public string DOB { get; set; }
        [StringLength(255)]
        public string Department { get; set; }
        [StringLength(255)]
        public string Designation { get; set; }
        [Column("Home Town")]
        [StringLength(100)]
        public string HomeTown { get; set; }
        [Column("D.O.J.")]
        [StringLength(10)]
        public string DOJ { get; set; }
        [Column("D.O.L.")]
        [StringLength(10)]
        public string DOL { get; set; }
        [Column("Resignation Date")]
        [StringLength(10)]
        public string ResignationDate { get; set; }
        [Column("Name of Bank")]
        [StringLength(2147483647)]
        public string NameofBank { get; set; }
        [Column("A/c No.")]
        [StringLength(2147483647)]
        public string AcNo { get; set; }
        [Column("IFSC Code")]
        [StringLength(2147483647)]
        public string IFSCCode { get; set; }
        [Column("Permanent Addess")]
        [StringLength(500)]
        public string PermanentAddess { get; set; }
        [Column("Present Address")]
        [StringLength(500)]
        public string PresentAddress { get; set; }
        [Column("Mob No.")]
        [StringLength(2147483647)]
        public string MobNo { get; set; }
        [Column("Phone No.")]
        [StringLength(10)]
        public string PhoneNo { get; set; }
        [Column("Email Id")]
        [StringLength(150)]
        public string EmailId { get; set; }
        [Column("Aadhar No.")]
        [StringLength(20)]
        public string AadharNo { get; set; }
        [Column("PAN No.")]
        [StringLength(15)]
        public string PANNo { get; set; }
        [StringLength(2147483647)]
        public string Qualification { get; set; }
        [Column("Father's Name")]
        [StringLength(100)]
        public string FathersName { get; set; }
        [Column("Mothers Name")]
        [StringLength(100)]
        public string MothersName { get; set; }
        [Column("Marital Status")]
        [StringLength(20)]
        public string MaritalStatus { get; set; }
        [Column("CHILD NAME")]
        [StringLength(2147483647)]
        public string CHILDNAME { get; set; }
        [StringLength(2147483647)]
        public string Relation { get; set; }
        [Column("CHILD DOB")]
        [StringLength(10)]
        public string CHILDDOB { get; set; }
        [StringLength(2147483647)]
        public string Company { get; set; }
        [Column("Joining Salary")]
        [StringLength(30)]
        public string JoiningSalary { get; set; }
        [Column("Annual CTC")]
        [StringLength(30)]
        public string AnnualCTC { get; set; }
        [Column("Sal Structure")]
        [StringLength(2)]
        public string SalStructure { get; set; }
        [Column("D.O.J.Group")]
        [StringLength(2)]
        public string DOJGroup { get; set; }
        [Column("P.F. Applicable?")]
        [StringLength(2)]
        public string PFApplicable { get; set; }
        [Column("P.F. Code?")]
        [StringLength(2)]
        public string PFCode { get; set; }
        [Column("P.F. No.")]
        [StringLength(2)]
        public string PFNo { get; set; }
        [Column("Previous P.F. No.")]
        [StringLength(2)]
        public string PreviousPFNo { get; set; }
        [Column("E.S.I. Applicable?")]
        [StringLength(2)]
        public string ESIApplicable { get; set; }
        [Column("E.S.I. No.")]
        [StringLength(2)]
        public string ESINo { get; set; }
        [Column("Universal A/c Number")]
        [StringLength(2147483647)]
        public string UniversalAcNumber { get; set; }
        [Column("Basic Salary")]
        [StringLength(30)]
        public string BasicSalary { get; set; }
        [Column("D.A.")]
        [StringLength(30)]
        public string DA { get; set; }
        [Column("H.R.A.")]
        [StringLength(30)]
        public string HRA { get; set; }
        [Column("C.C.A.")]
        [StringLength(30)]
        public string CCA { get; set; }
        [StringLength(2)]
        public string Conveyance { get; set; }
        [Column("Medical Allowance")]
        [StringLength(2)]
        public string MedicalAllowance { get; set; }
        [StringLength(2)]
        public string Incentive { get; set; }
        [Column("Fooding Allowance")]
        [StringLength(2)]
        public string FoodingAllowance { get; set; }
        [Column("Special Allowance")]
        [StringLength(30)]
        public string SpecialAllowance { get; set; }
        [Column("Extra Allowance")]
        [StringLength(30)]
        public string ExtraAllowance { get; set; }
        [Column("Leave Encashment")]
        [StringLength(2)]
        public string LeaveEncashment { get; set; }
        [Column("Medical Reim")]
        [StringLength(2)]
        public string MedicalReim { get; set; }
        [StringLength(2)]
        public string Lta { get; set; }
        [Column("Bonus/Ex-Gratia")]
        [StringLength(2)]
        public string BonusExGratia { get; set; }
        [StringLength(2)]
        public string Cca { get; set; }
        [Column("P.Tax")]
        [StringLength(2)]
        public string PTax { get; set; }
        [Column("L.W.F.")]
        [StringLength(2)]
        public string LWF { get; set; }
        [Column("Inc.Paid")]
        [StringLength(2)]
        public string IncPaid { get; set; }
        [StringLength(2)]
        public string Tds { get; set; }
        [StringLength(2)]
        public string Esi { get; set; }
        [StringLength(2)]
        public string Recovery { get; set; }
        [Column("Cash Short")]
        [StringLength(2)]
        public string CashShort { get; set; }
        [Column("Diesel Deduction")]
        [StringLength(2)]
        public string DieselDeduction { get; set; }
        [StringLength(2)]
        public string Penalty { get; set; }
        [StringLength(2)]
        public string Lwf { get; set; }
        [StringLength(2)]
        public string Medical { get; set; }
        [Column("Fuel & Maintenance")]
        [StringLength(2)]
        public string FuelMaintenance { get; set; }
        [Column("Books & Periodicals")]
        [StringLength(2)]
        public string BooksPeriodicals { get; set; }
        [Column("Professional Attire")]
        [StringLength(2)]
        public string ProfessionalAttire { get; set; }
        [Column("Driver Wages")]
        [StringLength(2)]
        public string DriverWages { get; set; }
        [Column("Meal Voucher")]
        [StringLength(2)]
        public string MealVoucher { get; set; }
        [Column("Gross Salary")]
        [StringLength(2)]
        public string GrossSalary { get; set; }
        [Column("Employeer PF")]
        [StringLength(2)]
        public string EmployeerPF { get; set; }
        [Column("Employeer ESI")]
        [StringLength(2)]
        public string EmployeerESI { get; set; }
        [Column("AC NO.2")]
        [StringLength(2)]
        public string ACNO2 { get; set; }
        [Column("AC NO.21")]
        [StringLength(2)]
        public string ACNO21 { get; set; }
        [StringLength(2)]
        public string GRATITY { get; set; }
        [Column("MONTHLY CTC.")]
        [StringLength(30)]
        public string MONTHLYCTC { get; set; }
        [Column("T.D.S.")]
        [StringLength(2)]
        public string TDS { get; set; }
        [Column("Payment Mode")]
        [StringLength(2)]
        public string PaymentMode { get; set; }
        [Column("Passport No.")]
        [StringLength(2)]
        public string PassportNo { get; set; }
        [Column("FATHER DOB")]
        [StringLength(2)]
        public string FATHERDOB { get; set; }
        [Column("MOTHER DOB")]
        [StringLength(2)]
        public string MOTHERDOB { get; set; }
        [Column("SPOUSE DOB")]
        [StringLength(2)]
        public string SPOUSEDOB { get; set; }
        [Column("CHILD NAME_2")]
        [StringLength(2)]
        public string CHILDNAME_2 { get; set; }
        [StringLength(2)]
        public string Relation_2 { get; set; }
        [Column("CHILD DOB_2")]
        [StringLength(2)]
        public string CHILDDOB_2 { get; set; }
        [Column("LIC No.")]
        [StringLength(2)]
        public string LICNo { get; set; }
        [Column("P.A.policy no.")]
        [StringLength(2)]
        public string PApolicyno { get; set; }
        [Column("Mediclaim No.")]
        [StringLength(2)]
        public string MediclaimNo { get; set; }
        [Column("Fooding Details")]
        [StringLength(2)]
        public string FoodingDetails { get; set; }
        [Column("Accomodation Details")]
        [StringLength(2)]
        public string AccomodationDetails { get; set; }
        [Column("Desig. Band")]
        [StringLength(2)]
        public string DesigBand { get; set; }
        [Column("Annual Gross")]
        [StringLength(2)]
        public string AnnualGross { get; set; }
        [Column("Hold Salary ?")]
        [StringLength(2)]
        public string HoldSalary { get; set; }
        [Column("Hold Reason/Remark")]
        [StringLength(2)]
        public string HoldReasonRemark { get; set; }
        [Column("Reimbursement A/c No.")]
        [StringLength(2)]
        public string ReimbursementAcNo { get; set; }
        [Column("Reimbursement Bank")]
        [StringLength(2)]
        public string ReimbursementBank { get; set; }
        [Column("Notice Days")]
        [StringLength(2)]
        public string NoticeDays { get; set; }
        [Column("Date of Confirmation")]
        [StringLength(2)]
        public string DateofConfirmation { get; set; }
        [Column("Gross Salary_2")]
        [StringLength(2)]
        public string GrossSalary_2 { get; set; }
        [StringLength(2)]
        public string branch { get; set; }
        [StringLength(2)]
        public string empstatus { get; set; }
        [StringLength(2)]
        public string trfreason { get; set; }
        [StringLength(2)]
        public string trfrdate { get; set; }
        [StringLength(2)]
        public string trfremark { get; set; }
        [StringLength(2)]
        public string senior { get; set; }
        [StringLength(2)]
        public string junior { get; set; }
        [StringLength(2)]
        public string icustomer { get; set; }
        [StringLength(2)]
        public string hod { get; set; }
        [StringLength(2)]
        public string rmanager { get; set; }
        [StringLength(2)]
        public string jbname { get; set; }
        [StringLength(2)]
        public string jobprofile { get; set; }
        [StringLength(2)]
        public string subdesig { get; set; }
        [StringLength(2)]
        public string sdsgrade { get; set; }
        [StringLength(10)]
        public string states { get; set; }
    }
}
