// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Hhbh
{
    public string Ecode { get; set; }

    public string Ename { get; set; }

    public string Gender { get; set; }

    public string Location { get; set; }

    public string Desig { get; set; }

    public string Dept { get; set; }

    public string Doj { get; set; }

    public string Dol { get; set; }

    public string Column1 { get; set; }
}