// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dc_Routing.Data.EFModels;

public partial class HRMS2Context : DbContext
{
    public HRMS2Context(DbContextOptions<HRMS2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Attendance> Attendances { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => e.DcAttendanceId).HasName("PK__Attendan__017282DF3EBBACBA");

            entity.ToTable("Attendance");

            entity.Property(e => e.Ecode).HasColumnName("ECode");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SubmitOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.EcodeNavigation).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.Ecode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_Employees");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Ecode).HasName("PK__Employee__7A63BD545CC388AC");

            entity.HasIndex(e => e.EmailId, "UQ__Employee__7ED91AEE1ADD7887").IsUnique();

            entity.Property(e => e.Ecode)
                .ValueGeneratedNever()
                .HasColumnName("ECode");
            entity.Property(e => e.ActInAct).HasDefaultValue(true);
            entity.Property(e => e.Department).HasMaxLength(100);
            entity.Property(e => e.Designation).HasMaxLength(100);
            entity.Property(e => e.EmailId)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("EmailID");
            entity.Property(e => e.EmpName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ReportingManagerName).HasMaxLength(100);
            entity.Property(e => e.RptPersonCard).HasMaxLength(50);
            entity.Property(e => e.SubDepartment).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}