// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class InsuranceEnrollment
{
    public string NameofInsured { get; set; }

    public string EmployeeId { get; set; }

    public string Relation { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public DateOnly? DateOfJoin { get; set; }

    public decimal? GrossSalary { get; set; }
}