// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Interviewer
{
    public int InterviewerId { get; set; }

    public int? RoundId { get; set; }

    public string Name { get; set; }

    public string Feedback { get; set; }

    public virtual InterviewRound Round { get; set; }
}