// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class InterviewRound
{
    public int RoundId { get; set; }

    public long? CandidateId { get; set; }

    public string RoundName { get; set; }

    public string Level { get; set; }

    public string Status { get; set; }

    public string Remark { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual ICollection<Interviewer> Interviewers { get; set; } = new List<Interviewer>();
}