// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Jd
{
    public int Jdid { get; set; }

    public int DesignationId { get; set; }

    public string KeyResponsibility { get; set; }

    public string KeySkills { get; set; }

    public virtual TblDesignation Designation { get; set; }
}