// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Newemployeemastertemp
{
    public string EmployeeCode { get; set; }

    public string NameOfEmployee { get; set; }

    public string PostedLocation { get; set; }

    public string JoinedLocation { get; set; }

    public string Sex { get; set; }

    public string DOB { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string HomeTown { get; set; }

    public string SalStructure { get; set; }

    public string DOJ { get; set; }

    public string DOJGroup { get; set; }

    public string DOL { get; set; }

    public string JoiningSalary { get; set; }

    public string PFApplicable { get; set; }

    public string PFCode { get; set; }

    public string PFNo { get; set; }

    public string PreviousPFNo { get; set; }

    public string ESIApplicable { get; set; }

    public string ESINo { get; set; }

    public string UniversalACNumber { get; set; }

    public string BasicSalary { get; set; }

    public string DA { get; set; }

    public string HRA { get; set; }

    public string CCA { get; set; }

    public string Conveyance { get; set; }

    public string MedicalAllowance { get; set; }

    public string Incentive { get; set; }

    public string FoodingAllowance { get; set; }

    public string SpecialAllowance { get; set; }

    public string ExtraAllowance { get; set; }

    public string LeaveEncashment { get; set; }

    public string MedicalReim { get; set; }

    public string Lta { get; set; }

    public string BonusExGratia { get; set; }

    public string Cca1 { get; set; }

    public string PTax { get; set; }

    public string LWF { get; set; }

    public string IncPaid { get; set; }

    public string Tds { get; set; }

    public string Esi { get; set; }

    public string Recovery { get; set; }

    public string CashShort { get; set; }

    public string DieselDeduction { get; set; }

    public string Penalty { get; set; }

    public string Lwf1 { get; set; }

    public string Medical { get; set; }

    public string FuelMaintenance { get; set; }

    public string BooksPeriodicals { get; set; }

    public string ProfessionalAttire { get; set; }

    public string DriverWages { get; set; }

    public string Mobile { get; set; }

    public string MealVoucher { get; set; }

    public string GrossSalary { get; set; }

    public string EmployeerPf { get; set; }

    public string EmployeerEsi { get; set; }

    public string AcNo2 { get; set; }

    public string AcNo21 { get; set; }

    public string Gratity { get; set; }

    public string MonthlyCtc { get; set; }

    public string TDS1 { get; set; }

    public string PaymentMode { get; set; }

    public string ACNo { get; set; }

    public string NameOfBank { get; set; }

    public string IfscCode { get; set; }

    public string PermanentAddess { get; set; }

    public string PresentAddress { get; set; }

    public string MobNo { get; set; }

    public string PhoneNo { get; set; }

    public string EmailId { get; set; }

    public string AadharNo { get; set; }

    public string PanNo { get; set; }

    public string PassportNo { get; set; }

    public string Qualification { get; set; }

    public string FatherSName { get; set; }

    public string FatherDob { get; set; }

    public string MothersName { get; set; }

    public string Relation { get; set; }

    public string MotherDob { get; set; }

    public string MaritalStatus { get; set; }

    public string SpouseDob { get; set; }

    public string ChildName { get; set; }

    public string Relation1 { get; set; }

    public string ChildDob { get; set; }

    public string ChildName1 { get; set; }

    public string Relation2 { get; set; }

    public string ChildDob1 { get; set; }

    public string LicNo { get; set; }

    public string PAPolicyNo { get; set; }

    public string MediclaimNo { get; set; }

    public string FoodingDetails { get; set; }

    public string AccomodationDetails { get; set; }

    public string DesigBand { get; set; }

    public string AnnualGross { get; set; }

    public string AnnualCtc { get; set; }

    public string HoldSalary { get; set; }

    public string HoldReasonRemark { get; set; }

    public string ReimbursementACNo { get; set; }

    public string ReimbursementBank { get; set; }

    public string ResignationDate { get; set; }

    public string NoticeDays { get; set; }

    public string DateOfConfirmation { get; set; }

    public string GrossSalary1 { get; set; }

    public string Company { get; set; }

    public string Branch { get; set; }

    public string Empstatus { get; set; }

    public string Trfreason { get; set; }

    public string Trfrdate { get; set; }

    public string Trfremark { get; set; }

    public string Senior { get; set; }

    public string Junior { get; set; }

    public string Icustomer { get; set; }

    public string Hod { get; set; }

    public string Rmanager { get; set; }

    public string Jbname { get; set; }

    public string Jobprofile { get; set; }

    public string Subdesig { get; set; }

    public string Sdsgrade { get; set; }

    public string States { get; set; }
}