// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class sp_SearchCandidatesResult
    {
        public long Id { get; set; }
        [StringLength(2147483647)]
        public string FirstName { get; set; }
        [StringLength(2147483647)]
        public string MiddleName { get; set; }
        [StringLength(2147483647)]
        public string LastName { get; set; }
        [StringLength(2147483647)]
        public string Phone { get; set; }
        [StringLength(2147483647)]
        public string Email { get; set; }
        [StringLength(2147483647)]
        public string Designation { get; set; }
        public DateOnly? Dob { get; set; }
        public int? StatusId { get; set; }
        public int? hrApprovalStatus { get; set; }
        public int? auditApprovalStatus { get; set; }
        public int? clusterManagerApprovalStatus { get; set; }
        [StringLength(255)]
        public string StoreLocationName { get; set; }
        [StringLength(2147483647)]
        public string StoreLocationCode { get; set; }
    }
}
