// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class StagingEmployee1
{
    public int? EmployeeId { get; set; }

    public int? CandidateId { get; set; }

    public string FilePath { get; set; }

    public string Title { get; set; }

    public string FullName { get; set; }

    public string FatherSName { get; set; }

    public string MotherSName { get; set; }

    public string PasportSizePhoto { get; set; }

    public DateOnly? Dob { get; set; }

    public string Gender { get; set; }

    public string PanNo { get; set; }

    public string AadharNo { get; set; }

    public string NameOnAdhar { get; set; }

    public string PlaceOfBirth { get; set; }

    public string PresentAddress { get; set; }

    public string PresentAddressPinCode { get; set; }

    public string PermanentAddress { get; set; }

    public string MaritialStatus { get; set; }

    public string Mobile { get; set; }

    public string EmailAddress { get; set; }

    public string Nationality { get; set; }

    public string Religion { get; set; }

    public string BankName { get; set; }

    public string ACNo { get; set; }

    public string BankIfscCode { get; set; }

    public string Reference1OfLast3Company { get; set; }

    public string Contact1OfLast3Company { get; set; }

    public string Reference2OfLast3Company1 { get; set; }

    public string Contact2OfLast3Company1 { get; set; }

    public string Reference3OfLast3Company11 { get; set; }

    public string Contact3OfLast3Company11 { get; set; }

    public string Reference4OfLast3Company11 { get; set; }

    public string Contact4OfLast3Company11 { get; set; }

    public string Reference5OfLast3Company111 { get; set; }

    public string Contact5OfLast3Company111 { get; set; }

    public string FamilyMemberName { get; set; }

    public string FamilyMemberRelation { get; set; }

    public DateOnly? FamilyMemberDob { get; set; }

    public string Company1 { get; set; }

    public string Company2 { get; set; }

    public string Company3 { get; set; }

    public string WorkLocation { get; set; }

    public string PositionHeldInPreviousCompany { get; set; }

    public DateOnly? From { get; set; }

    public DateOnly? To { get; set; }

    public decimal? InHandSalary { get; set; }

    public decimal? LastCtcAnnual { get; set; }

    public string HighestQualification { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsSalarySlipUploaded { get; set; }

    public bool? IsBankStatementUploaded { get; set; }

    public bool? IsPrevOfferLetterUploaded { get; set; }

    public bool? IsPassportPhotoUploaded { get; set; }

    public bool? IsPanAttachmentUploaded { get; set; }

    public bool? IsAadharAttachmentUploaded { get; set; }

    public bool? IsBankPassbookAttachmentUpoaded { get; set; }

    public bool? IsEducationAttachmentUploaded { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string Udf4 { get; set; }

    public string Udf5 { get; set; }

    public string Udf6 { get; set; }

    public string Udf7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public string Ecode { get; set; }

    public int? DesignationId { get; set; }

    public int? DepartmentId { get; set; }

    public int? LocationId { get; set; }

    public DateOnly? Doj { get; set; }

    public DateOnly? DateOfResignation { get; set; }

    public DateOnly? DateOfLeft { get; set; }

    public bool? Isresgined { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string ReportHeadEcode { get; set; }
}