// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class Store
{
    public int StoresId { get; set; }

    public string StoreName { get; set; }

    public string StoreCode { get; set; }

    public string OpeningMonth { get; set; }

    public string OpeningDate { get; set; }

    public string Cluster { get; set; }

    public string Address { get; set; }

    public string Region { get; set; }

    public string Zone { get; set; }

    public string State { get; set; }

    public decimal? Area { get; set; }

    public DateTime? LastUpdated { get; set; }

    public long? CreatedBy { get; set; }
}