// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class StoreLocation
{
    public int StoreLocationsId { get; set; }

    public string NameOfLocation { get; set; }

    public string LocationIncharge { get; set; }

    public string Address { get; set; }

    public string Sapcode { get; set; }

    public string Zone { get; set; }

    public bool? BillingOver50Lac { get; set; }

    public string Pfcode { get; set; }

    public string Esicode { get; set; }

    public string Type { get; set; }

    public int StateId { get; set; }

    public string WeeklyOff { get; set; }

    public string EmailId { get; set; }

    public string ErpsiteNameCode { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastupdatedBy { get; set; }

    public int? LocationId { get; set; }

    public virtual TblLocation Location { get; set; }

    public virtual State State { get; set; }

    public virtual ICollection<TblStoreBudget> TblStoreBudgets { get; set; } = new List<TblStoreBudget>();
}