// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class StoreMasterBulk
{
    public string Deptsno { get; set; }

    public string Loc { get; set; }

    public string Company { get; set; }

    public string Region { get; set; }

    public string Cl { get; set; }

    public string Subdeptsno { get; set; }

    public string Subdept { get; set; }

    public string Desgsno { get; set; }

    public string Desg { get; set; }

    public string Ss { get; set; }

    public string Seatmasterno { get; set; }

    public string EmpCode { get; set; }

    public string NameOfEmployee { get; set; }

    public string EMailId { get; set; }

    public string ContactNo { get; set; }

    public string Gender { get; set; }

    public string DOB { get; set; }

    public string DOJ { get; set; }

    public string Role { get; set; }

    public string Kra { get; set; }

    public string Kpi { get; set; }

    public string Trainingcontent { get; set; }

    public string Yesno { get; set; }

    public string Goal { get; set; }

    public string Grade { get; set; }

    public string ReportingManagerDesg { get; set; }

    public string ReportingManagerNm { get; set; }

    public string ReportingManagerMailId { get; set; }

    public string ReportingManagerContactNo { get; set; }
}