// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblAttendanceApproval
{
    public int ApprovalId { get; set; }

    public string ApproverEcode { get; set; }

    public string ApproverName { get; set; }

    public string ApproverDesg { get; set; }

    public string ApproverLoc { get; set; }

    public DateOnly? ApprovalDate { get; set; }

    public DateOnly? AttendanceDate { get; set; }

    public string ContractEmpCode { get; set; }

    public string ContractEmpName { get; set; }

    public string ContractEmpStatus { get; set; }

    public bool? IsApproved { get; set; }

    public virtual TblEmployee ApproverEcodeNavigation { get; set; }

    public virtual TblEmployee ContractEmpCodeNavigation { get; set; }
}