// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblCompOffRequest
{
    public int CompOffId { get; set; }

    public long? EmployeeId { get; set; }

    public DateOnly RequestedDate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public long? ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public virtual TblEmployee Employee { get; set; }
}