// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblDesignation
{
    public int DesignationId { get; set; }

    public string DesignationName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<Jd> Jds { get; set; } = new List<Jd>();

    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();

    public virtual ICollection<TblStoreBudget> TblStoreBudgets { get; set; } = new List<TblStoreBudget>();
}