// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblDcattendance
{
    public string Ecode { get; set; }

    public DateOnly? AttendanceDate { get; set; }

    public bool? Status { get; set; }

    public DateTime? SubmitOn { get; set; }

    public long DcattendanceId { get; set; }
}