// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblEmployeeMultiPunchesCleaned
{
    public long? Id { get; set; }

    public string UserId { get; set; }

    public DateOnly PunchDate { get; set; }

    public string MachineType { get; set; }

    public string Punch1 { get; set; }

    public string Punch2 { get; set; }

    public string Punch3 { get; set; }

    public string Punch4 { get; set; }

    public string Punch5 { get; set; }

    public string Punch6 { get; set; }

    public string Punch7 { get; set; }

    public string Punch8 { get; set; }

    public string Punch9 { get; set; }

    public string Punch10 { get; set; }

    public string Punch11 { get; set; }

    public string Punch12 { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public int? NoOfPunches { get; set; }

    public int? TotalHours { get; set; }

    public TimeOnly? RegularizePunchIn { get; set; }

    public TimeOnly? RegularizePuncOut { get; set; }

    public bool? IsRegularize { get; set; }
}