// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblEmployeePunch
{
    public string UserId { get; set; }

    public DateOnly PunchDate { get; set; }

    public TimeOnly PunchTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }
}