// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblEmployeeRole
{
    public long EmployeeRoleId { get; set; }

    public long EmployeeId { get; set; }

    public int RoleId { get; set; }

    public DateTime? AssignedOn { get; set; }

    public string AssignedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public virtual TblEmployee Employee { get; set; }

    public virtual TblRole Role { get; set; }
}