// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblEmpAttendance
{
    public long EmpAttendanceId { get; set; }

    public string EmpCode { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public TimeOnly PunchIn { get; set; }

    public TimeOnly PunchOut { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool? IsRegularize { get; set; }

    public bool? IsonLeave { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public TimeOnly? RegularizePunchIn { get; set; }

    public TimeOnly? RegularizePuncOut { get; set; }
}