// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblEmployeeLeaveBalance
{
    public long EmployeeLeaveBalanceId { get; set; }

    public long EmployeeId { get; set; }

    public decimal? Balance { get; set; }

    public decimal? Used { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public decimal? CasualLeaveBalance { get; set; }

    public decimal? EarnedLeaveBalance { get; set; }

    public decimal? SickLeaveBalance { get; set; }

    public decimal? PaternityLeaveBalance { get; set; }

    public decimal? MaternityLeaveBalance { get; set; }

    public decimal? CompOffBalance { get; set; }

    public decimal? CasualLeaveAcquired { get; set; }

    public decimal? CasualLeaveUsed { get; set; }

    public decimal? EarnedLeaveAcquired { get; set; }

    public decimal? EarnedLeaveUsed { get; set; }

    public decimal? SickLeaveAcquired { get; set; }

    public decimal? SickLeaveUsed { get; set; }

    public decimal? PaternityLeaveAcquired { get; set; }

    public decimal? PaternityLeaveUsed { get; set; }

    public decimal? MaternityLeaveAcquired { get; set; }

    public decimal? MaternityLeaveUsed { get; set; }

    public decimal? CompOffAcquired { get; set; }

    public decimal? CompOffUsed { get; set; }

    public DateOnly? LastCreditedMonth { get; set; }

    public virtual TblEmployee Employee { get; set; }
}