// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblLeavePolicy
{
    public int LeavePolicyId { get; set; }

    public int? LeaveTypeId { get; set; }

    public string PolicyName { get; set; }

    public decimal? MaxLeavesPerYear { get; set; }

    public decimal? LeavesPerMonth { get; set; }

    public string ApplicableFor { get; set; }

    public bool? IsCarryForward { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public virtual TblLeaveType LeaveType { get; set; }
}