// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblLeaveType
{
    public int LeaveTypeId { get; set; }

    public string LeaveTypeName { get; set; }

    public virtual ICollection<TblLeavePolicy> TblLeavePolicies { get; set; } = new List<TblLeavePolicy>();

    public virtual ICollection<TblLeaveRequest> TblLeaveRequests { get; set; } = new List<TblLeaveRequest>();
}