// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblLocation
{
    public int LocationId { get; set; }

    public string LocationName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Stcode { get; set; }

    public int? StateId { get; set; }

    public virtual ICollection<AssignLocationHistory> AssignLocationHistories { get; set; } = new List<AssignLocationHistory>();

    public virtual TblState State { get; set; }

    public virtual ICollection<StoreLocation> StoreLocations { get; set; } = new List<StoreLocation>();

    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
}