// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblLeaveRequest
{
    public long LeaveRequestId { get; set; }

    public long? EmployeeId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Reason { get; set; }

    public int? StatusId { get; set; }

    public long? ReportingManagerId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string Udf4 { get; set; }

    public string Udf5 { get; set; }

    public string Udf6 { get; set; }

    public string Udf7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public int? LeaveTypeId { get; set; }

    public string Remarks { get; set; }

    public bool? IsRevoked { get; set; }

    public virtual TblEmployee Employee { get; set; }

    public virtual TblLeaveType LeaveType { get; set; }

    public virtual TblEmployee ReportingManager { get; set; }

    public virtual TblStatus Status { get; set; }
}