// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblNewCandidateApproval
{
    public long ApprovalId { get; set; }

    public long CandidateId { get; set; }

    public int? HrapprovalStatus { get; set; }

    public int? AuditApprovalStatus { get; set; }

    public string HrreviewedBy { get; set; }

    public string AuditReviewedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string Udf4 { get; set; }

    public string Udf5 { get; set; }

    public string Udf6 { get; set; }

    public string Udf7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public int? ClusterManagerApprovalStatus { get; set; }

    public string ClusterManagerReviewBy { get; set; }

    public virtual TblStatus AuditApprovalStatusNavigation { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual TblStatus HrapprovalStatusNavigation { get; set; }
}