// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblRegion
{
    public int RegionId { get; set; }

    public string RegionName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<TblState> TblStates { get; set; } = new List<TblState>();
}