// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string Udf4 { get; set; }

    public string Udf5 { get; set; }

    public string Udf6 { get; set; }

    public string Udf7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public virtual ICollection<TblEmployeeRole> TblEmployeeRoles { get; set; } = new List<TblEmployeeRole>();
}