// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblStoreBudget
{
    public int StoreBudgetId { get; set; }

    public int StoreLocationsId { get; set; }

    public int DesignationId { get; set; }

    public int BudgetManpowerCount { get; set; }

    public decimal BudgetAmount { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastupdatedBy { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public virtual TblDesignation Designation { get; set; }

    public virtual StoreLocation StoreLocations { get; set; }
}