// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();

    public virtual ICollection<TblAttendanceRegularizationRequest> TblAttendanceRegularizationRequests { get; set; } = new List<TblAttendanceRegularizationRequest>();

    public virtual ICollection<TblLeaveRequest> TblLeaveRequests { get; set; } = new List<TblLeaveRequest>();

    public virtual ICollection<TblNewCandidateApproval> TblNewCandidateApprovalAuditApprovalStatusNavigations { get; set; } = new List<TblNewCandidateApproval>();

    public virtual ICollection<TblNewCandidateApproval> TblNewCandidateApprovalHrapprovalStatusNavigations { get; set; } = new List<TblNewCandidateApproval>();
}