// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblState
{
    public int StateId { get; set; }

    public string StateName { get; set; }

    public int RegionId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual TblRegion Region { get; set; }

    public virtual ICollection<TblLocation> TblLocations { get; set; } = new List<TblLocation>();
}