// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TblTravelRequest
{
    public int TravelRequestId { get; set; }

    public long EmployeeId { get; set; }

    public string LocationFrom { get; set; }

    public string LocationTo { get; set; }

    public string ModeOfTravel { get; set; }

    public string PurposeOfVisit { get; set; }

    public string RecommendedBy { get; set; }

    public string CreatedBy { get; set; }

    public string Remarks { get; set; }

    public string CurrentStatus { get; set; }

    public string IdproofFilePath { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public virtual TblEmployee Employee { get; set; }

    public virtual ICollection<TravelRequestAction> TravelRequestActions { get; set; } = new List<TravelRequestAction>();
}