// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TempEmpAttendance
{
    public string EmpCode { get; set; }

    public DateOnly? AttendanceDate { get; set; }

    public TimeOnly? PunchIn { get; set; }

    public TimeOnly? PunchOut { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }
}