// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TempEcode
{
    public string StMngmt { get; set; }

    public string Column1 { get; set; }

    public string Column2 { get; set; }

    public string Column3 { get; set; }

    public string Column4 { get; set; }
}