// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TmpEmployeeUpdate
{
    public string EmployeeCode { get; set; }

    public string NameOfEmployee { get; set; }

    public string PostedLocation { get; set; }

    public string JoinedLocation { get; set; }
}