// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TravelRequest
{
    public int TrvalId { get; set; }

    public string EmployeeName { get; set; }

    public string Destination { get; set; }

    public DateOnly VisitToDate { get; set; }

    public DateOnly VisitfromDate { get; set; }

    public string VisitPurpose { get; set; }

    public decimal? TotalAmount { get; set; }

    public string ApproveStatus { get; set; }
}