// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dc_Routing.Data.EFModels;

public partial class TravelRequestAction
{
    public int TravelRequestActionId { get; set; }

    public int TravelRequestId { get; set; }

    public int? IsApprovedByHod { get; set; }

    public string Hodremarks { get; set; }

    public int? IsApprovedByAdmin { get; set; }

    public string AdminRemarks { get; set; }

    public int? IsApprovedByUser { get; set; }

    public string UserRemarks { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public virtual TblTravelRequest TravelRequest { get; set; }
}