// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dc_Routing.Data.EFModels
{
    public partial class usp_ProcessBulkEmployeeDataNewsResult
    {
        [StringLength(42)]
        public string Message { get; set; }
    }
}
